---
#
# チュートリアル: 別の AWS アカウント の VPC とピア接続する - AWS CloudFormation
# https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/peer-with-vpc-in-another-account.html
#

AWSTemplateFormatVersion: '2010-09-09'
Description: Create a VPC and a VPC Peering connection using the PeerRole to accept.

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
  PeerVPCAccountId:
    Type: String
    Default: AWS::NoValue
  PeerRoleArn:
    Type: String
    Default: AWS::NoValue
  PeerVPCId:
    Type: AWS::EC2::VPC::Id

  VpcPeeringConnectionName:
    Type: String
    Description: VPC peering connection name.

Conditions:
  IsCrossAcount: !Not [!Equals [!Ref PeerVPCAccountId, AWS::NoValue]]

Resources:
  vpcPeeringConnection:
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      VpcId: !Ref VpcId
      PeerVpcId: !Ref PeerVPCId
      PeerOwnerId: !If [IsCrossAcount, !Ref PeerVPCAccountId, !Ref AWS::AccountId]
      PeerRoleArn: !If [IsCrossAcount, !Ref PeerRoleArn, !Ref AWS::NoValue]
      Tags:
        - Key: Name
          Value: !Ref VpcPeeringConnectionName

Outputs:
  VPCPeeringConnectionId:
    Value: !Ref vpcPeeringConnection
