---
#
# チュートリアル: 別の AWS アカウント の VPC とピア接続する - AWS CloudFormation
# https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/peer-with-vpc-in-another-account.html
#

AWSTemplateFormatVersion: '2010-09-09'
Description: Create a VPC and an assumable role for cross account VPC peering.

Parameters:
  PeerRequesterAccountId:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id

Resources:
  peerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Principal:
              AWS: !Ref PeerRequesterAccountId
            Action:
              - 'sts:AssumeRole'
            Effect: Allow
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action: ec2:acceptVpcPeeringConnection
                Effect: Allow
                Resource:
                  Fn::Sub: arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:vpc/${VpcId}
              - Action: ec2:acceptVpcPeeringConnection
                Condition:
                  StringEquals:
                    ec2:AccepterVpc:
                      Fn::Sub: arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:vpc/${VpcId}
                Effect: Allow
                Resource:
                  Fn::Sub: >-
                    arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:vpc-peering-connection/*

Outputs:
  RoleARN:
    Value: !GetAtt peerRole.Arn
